<a href="https://colab.research.google.com/github/rifqireza/data-science/blob/main/clean-data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [78]:
data = pd.read_excel('template_misi.xlsx', skiprows=2, header=0)

data.head()

   No. Kode Produk Final      Kategori    Nama Produk  Harga Awal
0    1          BWH-0008       bAWAHan        Legging    195000.0
1    2          GUN-0012          GAUN       JUMPSUIT    267000.0
2    3         ATS-00004           NaN          BOXER         NaN
3    4          GUN-0013          gaun     MAXI Dress   7050000.0
4    5          BWH-0006       Bawahan   cELANA jeans    402000.0

In [79]:
data['Nama Produk'] = data['Nama Produk'].str.strip()
data['Nama Produk'] = data['Nama Produk'].str.title()
data['Kategori'] = data['Kategori'].str.strip()
data['Kategori'] = data['Kategori'].str.title()

for col in data.columns:
    if data[col].dtype == 'object':
        data[col] = data[col].str.replace(r'\s+', ' ', regex=True)

data = data.dropna()
data.tail()

    No. Kode Produk Final Kategori Nama Produk  Harga Awal
33   34          GUN-0015     Gaun     Overall    234000.0
35   36          GUN-0014     Gaun      Kaftan    276000.0
36   37          ATS-0005   Atasan       Jaket    801000.0
37   38          BWH-0007  Bawahan         Rok    288000.0
38   39          GUN-0011     Gaun       Dress    597000.0

In [80]:
data['Kode_Number'] = data['Kode Produk Final'].str.extract(r'(\d+)')
data['Kode_Number'] = data['Kode_Number'].astype(int)

data = data.sort_values(by='Kode_Number')
data.head()

    No. Kode Produk Final Kategori Nama Produk  Harga Awal  Kode_Number
10   11          ATS-0001   Atasan     T-Shirt    165000.0            1
31   32          ATS-0002   Atasan        Blus    192000.0            2
20   21          ATS-0003   Atasan      Kemeja    249000.0            3
14   15          ATS-0003   Atasan      Kemeja    249000.0            3
32   33          ATS-0004   Atasan     Sweater    231000.0            4

In [81]:
data = data[data['Kode Produk Final'].str.len() <= 8]
data = data.drop_duplicates(subset='Kode Produk Final', keep='first')
data['No.'] = range(1, len(data) + 1)
data.head()

    No. Kode Produk Final Kategori Nama Produk  Harga Awal  Kode_Number
10    1          ATS-0001   Atasan     T-Shirt    165000.0            1
31    2          ATS-0002   Atasan        Blus    192000.0            2
20    3          ATS-0003   Atasan      Kemeja    249000.0            3
32    4          ATS-0004   Atasan     Sweater    231000.0            4
28    5          ATS-0005   Atasan       Jaket    801000.0            5

In [82]:
# Assuming 'Harga Awal' is a column in your DataFrame
# Apply the logic and format the 'Harga Awal' column
def format_harga(harga):
    if harga > 1000000:
        harga = harga / 10
    elif harga < 10000:
        harga = harga * 10
    return "Rp {:,.0f}".format(harga)

data['Harga Awal'] = data['Harga Awal'].astype(int).apply(format_harga)
data.head()
data

,No.,Kode Produk Final,Kategori,Nama Produk,Harga Awal,Kode_Number
10,1,ATS-0001,Atasan,T-Shirt,"Rp 165,000",1
31,2,ATS-0002,Atasan,Blus,"Rp 192,000",2
20,3,ATS-0003,Atasan,Kemeja,"Rp 249,000",3
32,4,ATS-0004,Atasan,Sweater,"Rp 231,000",4
28,5,ATS-0005,Atasan,Jaket,"Rp 801,000",5
4,6,BWH-0006,Bawahan,Celana Jeans,"Rp 402,000",6
37,7,BWH-0007,Bawahan,Rok,"Rp 288,000",7
0,8,BWH-0008,Bawahan,Legging,"Rp 195,000",8
22,9,BWH-0009,Bawahan,Celana Panjang,"Rp 168,000",9
5,10,BWH-0010,Bawahan,Hot Pants,"Rp 153,000",10
38,11,GUN-0011,Gaun,Dress,"Rp 597,000",11
1,12,GUN-0012,Gaun,Jumpsuit,"Rp 267,000",12
3,13,GUN-0013,Gaun,Maxi Dress,"Rp 705,000",13
35,14,GUN-0014,Gaun,Kaftan,"Rp 276,000",14
33,15,GUN-0015,Gaun,Overall,"Rp 234,000",15
7,16,AKS-0016,Aksesoris,Kaus Kaki,"Rp 210,000",16
21,17,AKS-0017,Aksesoris,Syal,"Rp 135,000",17
15,18,AKS-0018,Aksesoris,Topi,"Rp 105,000",18
11,19,AKS-0019,Aksesoris,Ikat Pinggang,"Rp 75,000",19
16,20,AKS-0020,Aksesoris,Kacamata,"Rp 246,000",20
18,21,OLR-0021,Pakaian Olahraga,Legging Olahraga,"Rp 195,000",21
30,22,OLR-0022,Pakaian Olahraga,Jersey,"Rp 231,000",22
25,23,OLR-0023,Pakaian Olahraga,Celana Pendek,"Rp 135,000",23
8,24,OLR-0024,Pakaian Olahraga,Kaos Olahraga,"Rp 132,000",24
27,25,OLR-0025,Pakaian Olahraga,Celana Training,"Rp 35,000",25

In [83]:
# Delete the 'Kode_Number' column
data = data.drop('Kode_Number', axis=1)

# Export the modified DataFrame to an Excel file
from google.colab import files
data.to_excel('modified_data.xlsx', index=False)
files.download('modified_data.xlsx')